name: zambad_flutter_web
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.6.3
  firebase_auth_web: ^5.5.3
  firebase_core: ^2.14.0
  flutter_mobx: ^2.0.6+5
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  mobx: ^2.1.3
  provider: ^6.0.5

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  mobx_codegen: ^2.1.1
  lint: ^2.1.2

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/fonts/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Nunito-VariableFont_wght.ttf
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Italic-VariableFont_YTLC,opsz,wdth,wght.ttf
        - asset: assets/fonts/NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf
    - family: Saira
      fonts:
        - asset: assets/fonts/Saira-Regular.ttf
        - asset: assets/fonts/Saira-SemiBold.ttf
